server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prayer_chain
    username: postgres
    password: 78z9GdU4x3Xh
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

